version: '3.8'

services:
  db:
    image: mysql:8.0 # Garantindo que é MySQL e não MariaDB
    container_name: mysql_lab
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: banco
      # MYSQL_USER: aluno
      # MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      # O volume nomeado gerencia os dados do banco sem problemas de permissão
      - db_data:/var/lib/mysql
      # Mapeia a pasta local 'banco' para inicialização automática
      - ./banco:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache_lab
    restart: always
    ports:
      - "81:80"
    volumes:
      # Mapeia a pasta local 'html' onde os alunos colocarão o código PHP
      - ./html:/var/www/html
    depends_on:
      - db

volumes:
  # Declaração do volume nomeado para os dados do MySQL
  db_data:
